### ISSUE TITLE
Port to sugar3.speech

### ISSUE THREAD

**Issue by quozl** [sugarlabs/readetexts#8]
ReadETexts uses the GStreamer [eSpeak plugin](https://github.com/sugarlabs/gst-plugins-espeak) directly and relies on handling the _espeak-mark_ message to do word highlighting.

Porting to `sugar3.speech` will require adding _espeak-mark_ message handling to `sugar3.speech`, or exposing the pipeline to the caller to let the activity add their own handler.

**Comment by quozl** [comment]
I've changed my mind on this.  At the time I created the issue I did not know what the activity was for.  Long term, I'd prefer that the Get Books activity acquire the features of this activity, so I've raised https://github.com/sugarlabs/get-books-activity/issues/30.  I'll close this issue now, but that doesn't stop anyone from working on it if they want to.  :grin:

**Comment by jdsimmons** [comment]
James,

Get Books was my first attempt at an Activity. I had participated in the
Give One Get One and had intended to use my new laptop to read the plain
text files provided by Project Gutenberg. I was disappointed to find that
the only thing the Read Activity could view at the time was PDF's, and I
didn't realize that there were websites where you could get PG books
converted from Plain Text to PDF.

Writing the Activity was a good way to learn about Sugar. I found that if
you downloaded a Plain Text file to the Journal it would more likely open
in the Write Activity than it would in read Etexts. I also found out that
you could mark a file in the Journal as created by an Activity and that
Activity would open it by default from then on. Then I figured out how to
make it download Plain Text books to the Journal itself, and how to make it
read the books aloud, and how to highlight passages, and a bunch of other
stuff.

I believe that a lot of Read Etext code has found its way into Read and I'm
fine with that, since I copied a bunch of code from Read to make Read
Etexts. Everything I wrote back then was done to work around some
limitation of Sugar without modifying Sugar itself. I wouldn't be surprised
if most of these Activities have outlived their usefulness. I got a lot of
use out of them at the time.

James Simmons

**Comment by quozl** [comment]
Thanks James.  Yes, many core activities and Sugar itself have changed, and the older activities haven't been reviewed for functionality.  Instead we've had people;
* download the bundles from activities.sugarlabs.org and add them to GitHub,
* test,
* report these activities not working,
* ask for new releases,
* fix problems,
* port to GTK 3, or;
* (now) port to Python 3.

However these people haven't gone back to check if the functionality has been replaced.  And since much of this is done inside a repository in GitHub, the people who could help on sugar-devel@ don't hear about it, and don't comment.  It is an unfortunate situation.

I do appreciate your work creating these activities in the first place.
